###############################################
#                 EpicBuckets                 #
#               Made by Songoda               #
###############################################


# All default configuration files can be found on
# https://www.spigotmc.org/resources/epicbuckets-the-most-powerful-genbucket-plugin.50944/
# Please use 1.13+ material names, the plugin auto converts them to your server version

FACTIONS-SUPPORT: false # MassiveCore and Factions/FactionsUUID/SavageFactions is needed

WORLDGUARD-SUPPORT: false # WorldEdit and WorldGuard is needed

GRIEFPREVENTION-SUPPORT: false # GriefPrevention is needed

ENABLE-GENS-IN-WILDERNESS: true

ENCHANT: false # Enchant genbuckets in all guis

CLOSE-GUI-AFTER-PURCHASE: false # Close the inventory after purchase

INFINITE-USE: false # If enabled, you won't lose a genbucket when you place it down
CHARGE-FOR-INFINITE-USE: false # This requires infinite use to be enabled and will charge the player when placing a genbucket
COST-FOR-INFINITE-USE: 400 # Money charged for placing a genbucket when the above is enabled

GENBUCKET-DELAY: 10 # Ticks delay between genbucket placements, 20 ticks = 1 second, set to 0 for no delay

USE-SPONGE-SUPPORT: false # If a sponge is found it will stop the genbucket
SPONGE-RADIUS: 3 # <- SPONGE-RADIUS 3 == 3x3. I do not recommending putting this higher than 3

MAX-ACTIVE-GEN-PER-PLAYER: 10 # Amount of gens a player can have active at time

PLACE-UNLIMTED-GENS: true # This will override MAX-ACTIVE-GEN-PER-PLAYER and let them place unlimted gens

MAX-VERTICAL-HEIGHT: 50 # Vertical gen height, the gen will stop if y > 256

MAX-HORIZONTAL-LENGTH: 50 # Horizontal height

DELAY: 5 # If delay is set to 20 it will place one block every second. 10 will place two blocks each second

DISABLE-GENBUCKETS: false # If enabled placing any genbuckets wont be placeable

CUSTOM-ACTIVE-GEN-PER-PLAY: # Put the highest first
# Everyone with the permission genbucket.limit.god
# will be able to place 30 instead of the default value (MAX-ACTIVE-GEN-PER-PLAYER)
  GOD: "30:genbucket.limit.god"
  VETERAN: "25:genbucket.limit.veteran"
  VIP: "20:genbucket.limit.vip"

# Valid values are: UP, DOWN, SOUTH, NORTH, EAST, WEST
# Whitelist means what faces the genbucket will work on
# Default means when, for example, you allow a vertical genbucket to work on a side that is different from
# UP or DOWN, the plugin will then get this value to allow the genbucket to work. Please make sure this value
# is logical. For the vertical genbucket, that would be either UP or DOWN. Any other value just makes it
# act like a horizontal genbucket, which ofcourse isnt going to work

VALID-FACES:
  HORIZONTAL:
    WHITELIST:
      - "EAST"
      - "WEST"
      - "NORTH"
      - "SOUTH"
    DEFAULT: "NORTH"
  VERTICAL:
    WHITELIST:
      - "UP"
      - "DOWN"
    DEFAULT: "UP"
  PSUEDO:
    WHITELIST:
      - "UP"
      - "DOWN"
    DEFAULT: "UP"
  INFUSED:
    WHITELIST:
      - "EAST"
      - "WEST"
      - "NORTH"
      - "SOUTH"
    DEFAULT: "NORTH"

# All genbuckets will run over these materials
# except the psuedo.
# Make all words capital!

IGNORE-MATERIALS:
  - "AIR" # <- Don't remove unless you know what you're doing

PSUEDO-MATERIALS: # Which materials should the psuedo genbucket work on?
  - "cobblestone"
  - "sand"
  - "obsidian"

FILL-ITEM:

  name: " "

  material: WHITE_STAINED_GLASS_PANE

BACK-BUTTON:

  name: " &c&lReturn back to categories"

  material: BARRIER


BULK-SHOP-INVENTORY:

  inventory-name: "Bulk shop for {player}"

  size: 6 # Number of lines in inventory

  fill: false # recommended off

  return-back-slot: 49

  main-item-slot: 22

  increase-item:

    material: GREEN_STAINED_GLASS_PANE

    slots: "24,25,26" # Put only three integers and separate with commas

  decrease-item:

    material: RED_STAINED_GLASS_PANE

    slots: "18,19,20" # Put only three integers and separate with commas

  purchase-item:

    name: "&a&lConfirm"

    material: YELLOW_STAINED_GLASS

    slot: 40


# All material names can be found @ https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

MENU-ITEMS:

  size: 3

  fill: true # Fill inventory ?

  inventory-name: "Select a category"

  '1': # Must be unique

    item: # Item configuration

      material: WATER_BUCKET # material name

      name: "&eVertical genbuckets" # Name of the item

      lore: # Lore of the item
        - ""
        - "&7&o(( Click to open shop ))"
        - ""
        - "&7Use vertical genbuckets to create"
        - "&7vertical walls fast and efficient"
        - ""

    shop: "vertical" # make a shop in shops.yml

    slot: 10 # slot in the gui

  '2':

    item:

      material: WATER_BUCKET

      name: "&eHorizontal genbuckets"

      lore:
        - ""
        - "&7&o(( Click to open shop ))"
        - ""
        - "&7Use horizontal genbuckets to create"
        - "&7roofs & floors fast and efficient"
        - ""

    shop: "horizontal"

    slot: 12 # slot in the gui

  '3':

    item:

      material: WATER_BUCKET

      name: "&eInfused genbuckets"

      lore:
        - ""
        - "&7&o(( Click to open shop ))"
        - ""
        - "&7Use infused genbuckets to place"
        - "&7vertical walls on each side of the"
        - "&7block"
        - ""

    shop: "infused"

    slot: 14 # slot in the gui

  '4':

    item:

      material: WATER_BUCKET

      name: "&ePsuedo genbuckets"

      lore:
        - ""
        - "&7&o(( Click to open shop ))"
        - ""
        - "&7Use psuedo genbuckets to repair"
        - "&7broken walls"
        - ""

    shop: "psuedo"

    slot: 16 # slot in the gui