name: EpicBuckets
version: maven-version-number
description: Generate walls fast and efficient with beautiful guis!
author: Songoda
main: com.songoda.epicbuckets.EpicBuckets
softdepend: [WorldGuard, WorldEdit, Factions, MassiveCore, GriefPrevention]
depend: [Vault]
commands:
  EpicBuckets:
    description: Main command.
    default: true
    aliases: [eb, genbucket, gen]
    usage: /<command> [reload]