###############################################
#                 EpicBuckets                 #
#               Made by Songoda               #
###############################################


# All config files can be found on
# https://www.spigotmc.org/resources/ezbucket-1-7-1-12-region-support-gui-horizontal-vertical-and-infused-gens-genbucket.50944/

FACTIONS-SUPPORT: false # MassiveCore and Factions/FactionsUUID/SavageFactions is needed

WORLDGUARD-SUPPORT: false # WorldEdit and WorldGuard is needed

GRIEFPREVENTION-SUPPORT: false # GriefPrevention is needed

ENABLE-GENS-IN-WILDERNESS: true

ENCHANT: false # Enchant genbuckets in all guis

CLOSE-GUI-AFTER-PURCHASE: false # Close the inventory after purchase

INFINITE-USE: false # If enabled, you won't lose a genbucket when you place it down

USE-SPONGE-SUPPORT: false # If a sponge is found it will stop the genbucket
SPONGE-RADIUS: 3 # <- SPONGE-RADIUS 3 == 3x3. I do not recommending putting this higher than 3

MAX-ACTIVE-GEN-PER-PLAYER: 10 # Amount of gens a player can have active at time

PLACE-UNLIMTED-GENS: true # This will override MAX-ACTIVE-GEN-PER-PLAYER and let them place unlimted gens

MAX-VERTICAL-HEIGHT: 257 # Vertical gen height, the gen will stop if y > 256

MAX-HORIZONTAL-LENGTH: 50 # Horizontal height

DELAY: 10 # If delay is set to 20 it will place one block every second. 10 will place two blocks each second

DISABLE-GENBUCKETS: false # If enabled placing any genbuckets wont be placeable

CUSTOM-ACTIVE-GEN-PER-PLAY: # Put the highest first
# Everyone with the permission genbucket.limit.god
# will be able to place 30 instead of the default value (MAX-ACTIVE-GEN-PER-PLAYER)
  GOD: "30:genbucket.limit.god"
  VETERAN: "25:genbucket.limit.veteran"
  VIP: "20:genbucket.limit.vip"

# All genbuckets will run over these materials
# except the psuedo.
# Make all words capital!

IGNORE-MATERIALS:
  - "AIR" # <- Don't remove unless you know what you're doing
  - "SNOW"
  - "LONG_GRASS"
  - "DEAD_BUSH"
  - "YELLOW_FLOWER"
  - "DOUBLE_PLANT"
  - "RED_ROSE"

PSUEDO-MATERIALS: # Which materials should the psuedo genbucket work on?
  - "cobblestone"
  - "sand"
  - "obsidian"

FILL-ITEM:

  name: " "

  material: stained_glass_pane

  damage: 15

BACK-BUTTON:

  name: " &c&lReturn back to categories"

  material: barrier

  damage: 0


BULK-SHOP-INVENTORY:

  inventory-name: "Bulk shop for {player}"

  size: 54 # Must be one of these: 9, 18, 27, 36, 45, 54

  fill: false # recommended off

  return-back-slot: 49

  main-item-slot: 22

  increase-item:

    material: stained_glass_pane

    damage: 5

    slots: "24,25,26" # Put only three integers and separate with commas

  decrease-item:

    material: stained_glass_pane

    damage: 14

    slots: "18,19,20" # Put only three integers and separate with commas

  purchase-item:

    name: "&a&lConfirm"

    material: stained_glass

    damage: 13

    slot: 40


# All material names can be found @ https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

MENU-ITEMS:

  size: 27 # Must be one of these: 9, 18, 27, 36, 45, 54

  fill: true # Fill inventory ?

  inventory-name: "Select a category"

  '1': # Must be unique

    item: # Item configuration

      material: WATER_BUCKET # material name

      damage: 0 # also known as short

      name: "&eVertical genbuckets" # Name of the item

      lore: # Lore of the item
        - ""
        - "&7&o(( Click to open shop ))"
        - ""
        - "&7Use vertical genbuckets to create"
        - "&7vertical walls fast and efficient"
        - ""

    shop: "vertical" # make a shop in shops.yml

    slot: 10 # slot in the gui

  '2':

    item:

      material: WATER_BUCKET

      damage: 0

      name: "&eHorizontal genbuckets"

      lore:
        - ""
        - "&7&o(( Click to open shop ))"
        - ""
        - "&7Use horizontal genbuckets to create"
        - "&7roofs & floors fast and efficient"
        - ""

    shop: "horizontal"

    slot: 12 # slot in the gui

  '3':

    item:

      material: WATER_BUCKET

      damage: 0

      name: "&eInfused genbuckets"

      lore:
        - ""
        - "&7&o(( Click to open shop ))"
        - ""
        - "&7Use infused genbuckets to place"
        - "&7vertical walls on each side of the"
        - "&7block"
        - ""

    shop: "infused"

    slot: 14 # slot in the gui

  '4':

    item:

      material: WATER_BUCKET

      damage: 0

      name: "&ePsuedo genbuckets"

      lore:
        - ""
        - "&7&o(( Click to open shop ))"
        - ""
        - "&7Use psuedo genbuckets to repair"
        - "&7broken walls"
        - ""

    shop: "psuedo"

    slot: 16 # slot in the gui