name: EpicBuckets
version: 1
description: Generate walls fast and efficient with beautiful guis!
author: Songoda
main: com.songoda.epicbuckets.EpicBuckets
softdepend: [WorldGuard, WorldEdit, Factions, MassiveCore, FactionsUUID, GriefPrevention]
depend: [Vault]
commands:
  genbucket:
    description: Open EpicBuckets shop
    aliases: [gb, gen, genbuckets, ezbucket, epicbuckkets, genshop]
    usage: "/gb"
  genbucketadmin:
    description: Admin commands
    aliases: [gbadmin, genadmin, genbucketadmin, ezbucketadmin]
    usage: "/genbucketadmin"